
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_ETHER_H
#define DCE_HEADER_ETHER_H
// TODO add extern "C" ?
#include <ether.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                


#ifdef __cplusplus
}
#endif
#endif
