
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_TIME_H
#define DCE_HEADER_TIME_H
// TODO add extern "C" ?
#include <time.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_nanosleep (timespec const *,timespec *);

 char * dce_asctime (tm const *);


 char * dce_ctime (time_t const *);


 tm * dce_gmtime (time_t const *);







 int dce_timer_create (clockid_t,__restrict__ ::sigevent *,__restrict__ ::timer_t *);

 int dce_timer_settime (timer_t,int,__restrict__ ::itimerspec const *,__restrict__ ::itimerspec *);

 int dce_timer_gettime (timer_t,itimerspec *);

 void dce_tzset ();

 time_t dce_time (time_t *);


#ifdef __cplusplus
}
#endif
#endif
