
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_IFADDRS_H
#define DCE_HEADER_IFADDRS_H
// TODO add extern "C" ?
#include <ifaddrs.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_getifaddrs (ifaddrs * * __ifap);



#ifdef __cplusplus
}
#endif
#endif
