
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_DLFCN_H
#define DCE_HEADER_DLFCN_H
// TODO add extern "C" ?
#include <dlfcn.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void * dce_dlopen (char const * __file,int __mode) noexcept;

 void * dce_dlsym (__restrict__ void * __handle,__restrict__ char const * __name) noexcept;


#ifdef __cplusplus
}
#endif
#endif
