
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_STDLIB_H
                    #define DCE_HEADER_STDLIB_H
                    // TODO add extern "C" ?
                    #include <stdlib.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_atexit (void (*)(  ) );

extern long int dce_random ();

extern void dce_srandom (unsigned int);

extern int dce_rand ();

extern void dce_srand (unsigned int);

extern double dce_drand48 ();

extern double dce_erand48 (short unsigned int *);

extern long int dce_lrand48 ();

extern long int dce_nrand48 (short unsigned int *);

extern long int dce_mrand48 ();

extern long int dce_jrand48 (short unsigned int *);

extern void dce_srand48 (long int);

extern short unsigned int * dce_seed48 (short unsigned int *);

extern void dce_lcong48 (short unsigned int *);










extern void * dce_calloc (size_t,size_t);

extern void * dce_malloc (size_t);

extern void dce_free (void *);

extern void * dce_realloc (void *,size_t);





extern long int dce_strtol (__restrict__ char const *,__restrict__ char * *,int);

extern long long int dce_strtoll (__restrict__ char const *,__restrict__ char * *,int);

extern long unsigned int dce_strtoul (__restrict__ char const *,__restrict__ char * *,int);

extern long long unsigned int dce_strtoull (__restrict__ char const *,__restrict__ char * *,int);

extern double dce_strtod (__restrict__ char const *,__restrict__ char * *);

extern char * dce_getenv (char const *);

extern int dce_putenv (char *);

extern int dce_setenv (char const *,char const *,int);

extern int dce_unsetenv (char const *);

extern int dce_clearenv ();


extern void dce_abort ();

extern int dce_mkstemp (char *);

extern void dce_exit (int);



                    #ifdef __cplusplus
}
#endif
                    #endif
                    