
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SETJMP_H
#define DCE_HEADER_SETJMP_H
// TODO add extern "C" ?
#include <setjmp.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                


#ifdef __cplusplus
}
#endif
#endif
