
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_NETDB_H
#define DCE_HEADER_NETDB_H
// TODO add extern "C" ?
#include <netdb.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_getnameinfo (__restrict__ ::sockaddr const *,socklen_t,__restrict__ char *,socklen_t,__restrict__ char *,socklen_t,int);

 hostent * dce_gethostbyname (char const *);

 hostent * dce_gethostbyname2 (char const *,int);

 int dce_getaddrinfo (__restrict__ char const *,__restrict__ char const *,__restrict__ ::addrinfo const *,__restrict__ ::addrinfo * *);

 void dce_freeaddrinfo (addrinfo *);

 char const * dce_gai_strerror (int);




 void dce_herror (char const *);













#ifdef __cplusplus
}
#endif
#endif
