
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_FCNTL_H
                    #define DCE_HEADER_FCNTL_H
                    // TODO add extern "C" ?
                    #include <fcntl.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    
extern int dce_fcntl (int,int,...);

extern int dce_open (char const *,int,...);

extern int dce_open64 (char const *,int,...);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    