
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_GRP_H
#define DCE_HEADER_GRP_H
// TODO add extern "C" ?
#include <grp.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_initgroups (char const *,__gid_t);



#ifdef __cplusplus
}
#endif
#endif
