
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SCHED_H
#define DCE_HEADER_SCHED_H
// TODO add extern "C" ?
#include <sched.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_sched_yield () noexcept;


#ifdef __cplusplus
}
#endif
#endif
