
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STATVFS_H
#define DCE_HEADER_STATVFS_H
// TODO add extern "C" ?
#include <statvfs.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void dce_statvfs::statvfs ();


#ifdef __cplusplus
}
#endif
#endif
