
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SEMAPHORE_H
                    #define DCE_HEADER_SEMAPHORE_H
                    // TODO add extern "C" ?
                    #include <semaphore.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_sem_init (sem_t *,int,unsigned int);

extern int dce_sem_destroy (sem_t *);

extern int dce_sem_post (sem_t *);

extern int dce_sem_wait (sem_t *);

extern int dce_sem_timedwait (__restrict__ ::sem_t *,__restrict__ ::timespec const *);

extern int dce_sem_trywait (sem_t *);

extern int dce_sem_getvalue (__restrict__ ::sem_t *,__restrict__ int *);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    