
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SOCKET_H
#define DCE_HEADER_SOCKET_H
// TODO add extern "C" ?
#include <socket.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                

#ifdef __cplusplus
}
#endif
#endif
