
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STRING_H
#define DCE_HEADER_STRING_H
// TODO add extern "C" ?
#include <string.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                




















 char * dce_strdup (char const * __s) noexcept ;

 char * dce_strndup (char const * __string,size_t __n) noexcept ;



#ifdef __cplusplus
}
#endif
#endif
