
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_LOCALE_H
                    #define DCE_HEADER_LOCALE_H
                    // TODO add extern "C" ?
                    #include <locale.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern char * dce_setlocale (int,char const *);




                    #ifdef __cplusplus
}
#endif
                    #endif
                    