
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STDLIB_H
#define DCE_HEADER_STDLIB_H
// TODO add extern "C" ?
#include <stdlib.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_atexit (void (*)(  ) );

 long int dce_random ();

 void dce_srandom (unsigned int);

 int dce_rand ();

 void dce_srand (unsigned int);

 double dce_drand48 ();

 double dce_erand48 (short unsigned int *);

 long int dce_lrand48 ();

 long int dce_nrand48 (short unsigned int *);

 long int dce_mrand48 ();

 long int dce_jrand48 (short unsigned int *);

 void dce_srand48 (long int);

 short unsigned int * dce_seed48 (short unsigned int *);

 void dce_lcong48 (short unsigned int *);










 void * dce_calloc (size_t,size_t);

 void * dce_malloc (size_t);

 void dce_free (void *);

 void * dce_realloc (void *,size_t);





 long int dce_strtol (__restrict__ char const *,__restrict__ char * *,int);

 long long int dce_strtoll (__restrict__ char const *,__restrict__ char * *,int);

 long unsigned int dce_strtoul (__restrict__ char const *,__restrict__ char * *,int);

 long long unsigned int dce_strtoull (__restrict__ char const *,__restrict__ char * *,int);

 double dce_strtod (__restrict__ char const *,__restrict__ char * *);

 char * dce_getenv (char const *);

 int dce_putenv (char *);

 int dce_setenv (char const *,char const *,int);

 int dce_unsetenv (char const *);

 int dce_clearenv ();


 void dce_abort ();

 int dce_mkstemp (char *);

 void dce_exit (int);



#ifdef __cplusplus
}
#endif
#endif
