
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SYSLOG_H
                    #define DCE_HEADER_SYSLOG_H
                    // TODO add extern "C" ?
                    #include <syslog.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern void dce_openlog (char const *,int,int);

extern void dce_closelog ();

extern int dce_setlogmask (int);

extern void dce_syslog (int,char const *,...);

extern void dce_vsyslog (int,char const *,va_list);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    