
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_TIME_H
#define DCE_HEADER_TIME_H
// TODO add extern "C" ?
#include <time.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_nanosleep (timespec const * __requested_time,timespec * __remaining);

 char * dce_asctime (tm const * __tp);


 char * dce_ctime (time_t const * __timer);


 tm * dce_gmtime (time_t const * __timer);







 int dce_timer_create (clockid_t __clock_id,__restrict__ ::sigevent * __evp,__restrict__ ::timer_t * __timerid);

 int dce_timer_settime (timer_t __timerid,int __flags,__restrict__ ::itimerspec const * __value,__restrict__ ::itimerspec * __ovalue);

 int dce_timer_gettime (timer_t __timerid,itimerspec * __value);

 void dce_tzset ();

 time_t dce_time (time_t * __timer);


#ifdef __cplusplus
}
#endif
#endif
