
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_UNISTD_H
#define DCE_HEADER_UNISTD_H
// TODO add extern "C" ?
#include <unistd.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 ssize_t dce_read (int,void *,size_t);

 ssize_t dce_write (int,void const *,size_t);

 unsigned int dce_sleep (unsigned int);

 int dce_usleep (__useconds_t);

 __pid_t dce_getpid ();

 __pid_t dce_getppid ();

 __uid_t dce_getuid ();

 __uid_t dce_geteuid ();

 int dce_setuid (__uid_t);

 int dce_setgid (__gid_t);

 int dce_seteuid (__uid_t);

 int dce_setegid (__gid_t);

 int dce_setreuid (__uid_t,__uid_t);

 int dce_setregid (__gid_t,__gid_t);

 int dce_setresuid (__uid_t,__uid_t,__uid_t);

 int dce_setresgid (__gid_t,__gid_t,__gid_t);

 int dce_dup (int);

 int dce_dup2 (int,int);

 int dce_close (int);

 int dce_unlink (char const *);

 int dce_rmdir (char const *);

 int dce_isatty (int);

 char * dce_getcwd (char *,size_t);

 char * dce_getwd (char *);

 char * dce_get_current_dir_name ();

 int dce_chdir (char const *);

 int dce_fchdir (int);

 __pid_t dce_fork ();

 int dce_execv (char const *,char * const *);

 int dce_execl (char const *,char const *,...);

 int dce_execve (char const *,char * const *,char * const *);

 int dce_execvp (char const *,char * const *);

 int dce_execlp (char const *,char const *,...);

 int dce_execle (char const *,char const *,...);

 int dce_truncate (char const *,__off_t);

 int dce_ftruncate (int,__off_t);

 int dce_ftruncate64 (int,__off64_t);


 char * dce_ttyname (int);

 void * dce_sbrk (intptr_t);

 int dce_getpagesize ();

 __gid_t dce_getgid ();

 __gid_t dce_getegid ();

 int dce_gethostname (char *,size_t);

 __pid_t dce_getpgrp ();

 __off_t dce_lseek (int,__off_t,int);

 __off64_t dce_lseek64 (int,__off64_t,int);

 int dce_euidaccess (char const *,int);

 int dce_eaccess (char const *,int);

 int dce_access (char const *,int);

 int dce_pipe (int *);



 ssize_t dce_pread (int,void *,size_t,__off_t);

 ssize_t dce_pwrite (int,void const *,size_t,__off_t);

 int dce_daemon (int,int);

 unsigned int dce_alarm (unsigned int);

 ssize_t dce_readlink (__restrict__ char const *,__restrict__ char *,size_t);

 int dce_chown (char const *,__uid_t,__gid_t);

 int dce_fsync (int);

 int dce_unlinkat (int,char const *,int);


#ifdef __cplusplus
}
#endif
#endif
