
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_GETOPT_H
#define DCE_HEADER_GETOPT_H
// TODO add extern "C" ?
#include <getopt.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_getopt (int,char * const *,char const *);

 int dce_getopt_long (int,char * const *,char const *,option const *,int *);


#ifdef __cplusplus
}
#endif
#endif
