
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SYSINFO_H
                    #define DCE_HEADER_SYSINFO_H
                    // TODO add extern "C" ?
                    #include <sysinfo.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                     void dce_sysinfo::sysinfo ();


                    #ifdef __cplusplus
}
#endif
                    #endif
                    