
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_STDIO_H
                    #define DCE_HEADER_STDIO_H
                    // TODO add extern "C" ?
                    #include <stdio.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern FILE * dce_tmpfile ();

extern int dce_rename (char const *,char const *);

extern void dce_clearerr (FILE *);

extern int dce_setvbuf (__restrict__ ::FILE *,__restrict__ char *,int,size_t);

extern void dce_setbuf (__restrict__ ::FILE *,__restrict__ char *);

extern void dce_setbuffer (__restrict__ ::FILE *,__restrict__ char *,size_t);

extern void dce_setlinebuf (FILE *);

extern int dce_fseek (FILE *,long int,int);

extern long int dce_ftell (FILE *);

extern int dce_fseeko (FILE *,__off_t,int);

extern __off_t dce_ftello (FILE *);

extern void dce_rewind (FILE *);

extern int dce_fgetpos (__restrict__ ::FILE *,__restrict__ ::fpos_t *);

extern int dce_fsetpos (FILE *,fpos_t const *);

extern int dce_printf (__restrict__ char const *,...);



extern int dce_asprintf (__restrict__ char * *,__restrict__ char const *,...);

extern int dce_vasprintf (__restrict__ char * *,__restrict__ char const *,va_list);



extern int dce_fgetc (FILE *);



extern int dce_getchar ();

extern int dce_fputc (int,FILE *);



extern int dce_putchar (int);

extern char * dce_fgets (__restrict__ char *,int,__restrict__ ::FILE *);

extern int dce_fputs (__restrict__ char const *,__restrict__ ::FILE *);

extern int dce_puts (char const *);

extern int dce_ungetc (int,FILE *);

extern int dce_fclose (FILE *);

extern int dce_fcloseall ();

extern FILE * dce_fopen (__restrict__ char const *,__restrict__ char const *);

extern FILE * dce_fopen64 (__restrict__ char const *,__restrict__ char const *);

extern FILE * dce_freopen (__restrict__ char const *,__restrict__ char const *,__restrict__ ::FILE *);

extern FILE * dce_fdopen (int,char const *);

extern size_t dce_fread (__restrict__ void *,size_t,size_t,__restrict__ ::FILE *);

extern size_t dce_fwrite (__restrict__ void const *,size_t,size_t,__restrict__ ::FILE *);

extern int dce_ferror (FILE *);

extern int dce_feof (FILE *);

extern int dce_fileno (FILE *);

extern void dce_perror (char const *);

extern int dce_remove (char const *);




extern int dce_vprintf (__restrict__ char const *,va_list);




                    #ifdef __cplusplus
}
#endif
                    #endif
                    