
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_LIBIO_H
#define DCE_HEADER_LIBIO_H
// TODO add extern "C" ?
#include <libio.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce__IO_getc (_IO_FILE *);

 int dce__IO_putc (int,_IO_FILE *);


#ifdef __cplusplus
}
#endif
#endif
