
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_GETOPT_H
#define DCE_HEADER_GETOPT_H
// TODO add extern "C" ?
#include <getopt.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_getopt (int ___argc,char * const * ___argv,char const * __shortopts);

 int dce_getopt_long (int ___argc,char * const * ___argv,char const * __shortopts,option const * __longopts,int * __longind);


#ifdef __cplusplus
}
#endif
#endif
