
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_ERRNO_H
#define DCE_HEADER_ERRNO_H
// TODO add extern "C" ?
#include <errno.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int * dce___errno_location () noexcept ;


#ifdef __cplusplus
}
#endif
#endif
