
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SIGACTION_H
                    #define DCE_HEADER_SIGACTION_H
                    // TODO add extern "C" ?
                    #include <sigaction.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

//                     void dce_sigaction::sigaction ();


                    #ifdef __cplusplus
}
#endif
                    #endif
                    