
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STDIO_H
#define DCE_HEADER_STDIO_H
// TODO add extern "C" ?
#include <stdio.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 FILE * dce_tmpfile ();

 int dce_rename (char const *,char const *);

 void dce_clearerr (FILE *);

 int dce_setvbuf (__restrict__ ::FILE *,__restrict__ char *,int,size_t);

 void dce_setbuf (__restrict__ ::FILE *,__restrict__ char *);

 void dce_setbuffer (__restrict__ ::FILE *,__restrict__ char *,size_t);

 void dce_setlinebuf (FILE *);

 int dce_fseek (FILE *,long int,int);

 long int dce_ftell (FILE *);

 int dce_fseeko (FILE *,__off_t,int);

 __off_t dce_ftello (FILE *);

 void dce_rewind (FILE *);

 int dce_fgetpos (__restrict__ ::FILE *,__restrict__ ::fpos_t *);

 int dce_fsetpos (FILE *,fpos_t const *);

 int dce_printf (__restrict__ char const *,...);



 int dce_asprintf (__restrict__ char * *,__restrict__ char const *,...);

 int dce_vasprintf (__restrict__ char * *,__restrict__ char const *,va_list);



 int dce_fgetc (FILE *);



 int dce_getchar ();

 int dce_fputc (int,FILE *);



 int dce_putchar (int);

 char * dce_fgets (__restrict__ char *,int,__restrict__ ::FILE *);

 int dce_fputs (__restrict__ char const *,__restrict__ ::FILE *);

 int dce_puts (char const *);

 int dce_ungetc (int,FILE *);

 int dce_fclose (FILE *);

 int dce_fcloseall ();

 FILE * dce_fopen (__restrict__ char const *,__restrict__ char const *);

 FILE * dce_fopen64 (__restrict__ char const *,__restrict__ char const *);

 FILE * dce_freopen (__restrict__ char const *,__restrict__ char const *,__restrict__ ::FILE *);

 FILE * dce_fdopen (int,char const *);

 size_t dce_fread (__restrict__ void *,size_t,size_t,__restrict__ ::FILE *);

 size_t dce_fwrite (__restrict__ void const *,size_t,size_t,__restrict__ ::FILE *);

 int dce_fflush (FILE *);

 int dce_ferror (FILE *);

 int dce_feof (FILE *);

 int dce_fileno (FILE *);

 void dce_perror (char const *);

 int dce_remove (char const *);




 int dce_vprintf (__restrict__ char const *,va_list);






#ifdef __cplusplus
}
#endif
#endif
