
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_MMAN_H
                    #define DCE_HEADER_MMAN_H
                    // TODO add extern "C" ?
                    #include <mman.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern void * dce_mmap (void *,size_t,int,int,int,__off_t);

extern void * dce_mmap64 (void *,size_t,int,int,int,__off64_t);

extern int dce_munmap (void *,size_t);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    