
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_IOCTL_H
                    #define DCE_HEADER_IOCTL_H
                    // TODO add extern "C" ?
                    #include <ioctl.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_ioctl (int,long unsigned int,...);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    