
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_NL_TYPES_H
#define DCE_HEADER_NL_TYPES_H
// TODO add extern "C" ?
#include <nl_types.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                


#ifdef __cplusplus
}
#endif
#endif
