
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_STRING_H
                    #define DCE_HEADER_STRING_H
                    // TODO add extern "C" ?
                    #include <string.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    




















extern char * dce_strdup (char const *);

extern char * dce_strndup (char const *,size_t);



                    #ifdef __cplusplus
}
#endif
                    #endif
                    