
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_FCNTL_H
#define DCE_HEADER_FCNTL_H
// TODO add extern "C" ?
#include <fcntl.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                
 int dce_fcntl (int,int,...);

 int dce_open (char const *,int,...);

 int dce_open64 (char const *,int,...);

 int dce_creat (char const *,mode_t);


#ifdef __cplusplus
}
#endif
#endif
