
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SIGACTION_H
                    #define DCE_HEADER_SIGACTION_H
                    // TODO add extern "C" ?
                    #include <signal.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

int dce_sigaction(int signum, const struct sigaction *act, struct sigaction *oldact);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    