
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SELECT_H
                    #define DCE_HEADER_SELECT_H
                    // TODO add extern "C" ?
                    #include <select.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_select (int,__restrict__ ::fd_set *,__restrict__ ::fd_set *,__restrict__ ::fd_set *,__restrict__ ::timeval *);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    