
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_SIGNAL_H
                    #define DCE_HEADER_SIGNAL_H
                    // TODO add extern "C" ?
                    #include <signal.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern __sighandler_t dce_signal (int,__sighandler_t);






extern int dce_sigprocmask (int,__restrict__ ::sigset_t const *,__restrict__ ::sigset_t *);

extern int dce_sigwait (__restrict__ ::sigset_t const *,__restrict__ int *);

extern int dce_kill (__pid_t,int);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    