
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_FNMATCH_H
#define DCE_HEADER_FNMATCH_H
// TODO add extern "C" ?
#include <fnmatch.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                

#ifdef __cplusplus
}
#endif
#endif
