
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_DIRENT_H
#define DCE_HEADER_DIRENT_H
// TODO add extern "C" ?
#include <dirent.h>
#include <stdarg.h> // just in case there is an ellipsis
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 DIR * dce_opendir (char const * __name)  ;

 DIR * dce_fdopendir (int __fd)  ;

 dirent * dce_readdir (DIR * __dirp)  ;

 int dce_readdir_r (__restrict__ ::DIR * __dirp,__restrict__ ::dirent * __entry,__restrict__ ::dirent * * __result)  ;

 int dce_closedir (DIR * __dirp)  ;

 int dce_dirfd (DIR * __dirp) noexcept ;

 void dce_rewinddir (DIR * __dirp) noexcept ;

 int dce_scandir (__restrict__ char const * __dir,__restrict__ ::dirent * * * __namelist,int (*)( ::dirent const * ) ,int (*)( ::dirent const * *,::dirent const * * ) )  ;





#ifdef __cplusplus
}
#endif
#endif
