
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STDIO_EXT_H
#define DCE_HEADER_STDIO_EXT_H
// TODO add extern "C" ?
#include <stdio_ext.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void dce___fpurge (FILE *);

 size_t dce___fpending (FILE *);


#ifdef __cplusplus
}
#endif
#endif
