
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_WAITSTATUS_H
#define DCE_HEADER_WAITSTATUS_H
// TODO add extern "C" ?
#include <waitstatus.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void dce_wait::wait ();


#ifdef __cplusplus
}
#endif
#endif
