
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_PTHREAD_H
#define DCE_HEADER_PTHREAD_H
// TODO add extern "C" ?
#include <pthread.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_pthread_create (__restrict__ ::pthread_t *,__restrict__ ::pthread_attr_t const *,void * (*)( void * ) ,__restrict__ void *);

 void dce_pthread_exit (void *);

 pthread_t dce_pthread_self ();

 int dce_pthread_once (pthread_once_t *,void (*)(  ) );

 void * dce_pthread_getspecific (pthread_key_t);

 int dce_pthread_setspecific (pthread_key_t,void const *);

 int dce_pthread_key_create (pthread_key_t *,void (*)( void * ) );

 int dce_pthread_key_delete (pthread_key_t);

 int dce_pthread_mutex_destroy (pthread_mutex_t *);

 int dce_pthread_mutex_init (pthread_mutex_t *,pthread_mutexattr_t const *);

 int dce_pthread_mutex_lock (pthread_mutex_t *);

 int dce_pthread_mutex_unlock (pthread_mutex_t *);

 int dce_pthread_mutex_trylock (pthread_mutex_t *);

 int dce_pthread_mutexattr_init (pthread_mutexattr_t *);

 int dce_pthread_mutexattr_destroy (pthread_mutexattr_t *);

 int dce_pthread_mutexattr_settype (pthread_mutexattr_t *,int);

 int dce_pthread_cancel (pthread_t);

 int dce_pthread_join (pthread_t,void * *);

 int dce_pthread_detach (pthread_t);

 int dce_pthread_cond_destroy (pthread_cond_t *);

 int dce_pthread_cond_init (__restrict__ ::pthread_cond_t *,__restrict__ ::pthread_condattr_t const *);

 int dce_pthread_cond_broadcast (pthread_cond_t *);

 int dce_pthread_cond_signal (pthread_cond_t *);

 int dce_pthread_cond_timedwait (__restrict__ ::pthread_cond_t *,__restrict__ ::pthread_mutex_t *,__restrict__ ::timespec const *);

 int dce_pthread_cond_wait (__restrict__ ::pthread_cond_t *,__restrict__ ::pthread_mutex_t *);

 int dce_pthread_condattr_destroy (pthread_condattr_t *);

 int dce_pthread_condattr_init (pthread_condattr_t *);














#ifdef __cplusplus
}
#endif
#endif
