
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SIGNAL_H
#define DCE_HEADER_SIGNAL_H
// TODO add extern "C" ?
#include <signal.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 __sighandler_t dce_signal (int,__sighandler_t);

 int dce_sigaction (int signum, const struct sigaction *act, struct sigaction *oldact);






 int dce_sigprocmask (int,__restrict__ ::sigset_t const *,__restrict__ ::sigset_t *);

 int dce_sigwait (__restrict__ ::sigset_t const *,__restrict__ int *);

 int dce_kill (__pid_t,int);

 int dce_pthread_kill (pthread_t thread, int sig);


#ifdef __cplusplus
}
#endif
#endif
