
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_TIME_H
                    #define DCE_HEADER_TIME_H
                    // TODO add extern "C" ?
                    #include <time.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_nanosleep (timespec const *,timespec *);

extern char * dce_asctime (tm const *);


extern char * dce_ctime (time_t const *);


extern tm * dce_gmtime (time_t const *);







extern int dce_timer_create (clockid_t,__restrict__ ::sigevent *,__restrict__ ::timer_t *);

extern int dce_timer_settime (timer_t,int,__restrict__ ::itimerspec const *,__restrict__ ::itimerspec *);

extern int dce_timer_gettime (timer_t,itimerspec *);

extern void dce_tzset ();

extern time_t dce_time (time_t *);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    