
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STATFS_H
#define DCE_HEADER_STATFS_H
// TODO add extern "C" ?
#include <statfs.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void dce_statfs::statfs ();

 void dce_statfs64::statfs64 ();


#ifdef __cplusplus
}
#endif
#endif
