
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_STDIO2_H
#define DCE_HEADER_STDIO2_H
// TODO add extern "C" ?
//#include <stdio2.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce___printf_chk (int __flag,__restrict__ char const * __format,... ) ;

 int dce___vfprintf_chk (__restrict__ ::FILE * __stream,int __flag,__restrict__ char const * __format,va_list) ;

 int dce___fprintf_chk (__restrict__ ::FILE * __stream,int __flag,__restrict__ char const * __format,... ) ;

 int dce___snprintf_chk (__restrict__ char * __s,size_t __n,int __flag,size_t __slen,__restrict__ char const * __format,... ) noexcept;

 int dce___vsnprintf_chk (__restrict__ char * __s,size_t __n,int __flag,size_t __slen,__restrict__ char const * __format,va_list) noexcept;


#ifdef __cplusplus
}
#endif
#endif
