
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_UTSNAME_H
                    #define DCE_HEADER_UTSNAME_H
                    // TODO add extern "C" ?
                    #include <sys/utsname.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_uname (utsname *);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    