
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_INET_H
#define DCE_HEADER_INET_H
// TODO add extern "C" ?
#include <inet.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                






 char const * dce_inet_ntop (int __af,__restrict__ void const * __cp,__restrict__ char * __buf,socklen_t __len) noexcept;



#ifdef __cplusplus
}
#endif
#endif
