
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_STAT_H
                    #define DCE_HEADER_STAT_H
                    // TODO add extern "C" ?
                    #include <stat.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_mkdir (char const *,__mode_t);

extern __mode_t dce_umask (__mode_t);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    