
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_DIRENT_H
#define DCE_HEADER_DIRENT_H
// TODO add extern "C" ?
#include <dirent.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 DIR * dce_opendir (char const *);

 DIR * dce_fdopendir (int);

 dirent * dce_readdir (DIR *);

 int dce_readdir_r (__restrict__ ::DIR *,__restrict__ ::dirent *,__restrict__ ::dirent * *);

 int dce_closedir (DIR *);

 int dce_dirfd (DIR *);

 void dce_rewinddir (DIR *);

 int dce_scandir (__restrict__ char const *,__restrict__ ::dirent * * *,int (*)( ::dirent const * ) ,int (*)( ::dirent const * *,::dirent const * * ) );





#ifdef __cplusplus
}
#endif
#endif
