
                    /* DO NOT MODIFY - GENERATED BY script */
                    #ifndef DCE_HEADER_POLL_H
                    #define DCE_HEADER_POLL_H
                    // TODO add extern "C" ?
                    #include <poll.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif

                    extern int dce_poll (pollfd *,nfds_t,int);


                    #ifdef __cplusplus
}
#endif
                    #endif
                    