## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'tap-bridge','point-to-point', 'csma' ], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce',  'tap-bridge', 'point-to-point', 'csma' ],
				  target='bin/dce-ccn-vlc',
				  source=['dce-ccn-vlc.cc'],
				  )

