
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_POLL_H
#define DCE_HEADER_SYS_POLL_H
// TODO add extern "C" ?
#include <sys/poll.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_poll (pollfd * __fds,nfds_t __nfds,int __timeout);


#ifdef __cplusplus
}
#endif
#endif
