
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_STAT_H
#define DCE_HEADER_SYS_STAT_H
// TODO add extern "C" ?
#include <sys/stat.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_mkdir (char const * __path,__mode_t __mode) noexcept;

 __mode_t dce_umask (__mode_t __mask) noexcept;

 int dce___xstat (int __ver,char const * __filename,stat * __stat_buf) noexcept;

 int dce___lxstat (int __ver,char const * __filename,stat * __stat_buf) noexcept;

 int dce___fxstat (int __ver,int __fildes,stat * __stat_buf) noexcept;

 int dce___xstat64 (int __ver,char const * __filename,stat64 * __stat_buf) noexcept;

 int dce___lxstat64 (int __ver,char const * __filename,stat64 * __stat_buf) noexcept;

 int dce___fxstat64 (int __ver,int __fildes,stat64 * __stat_buf) noexcept;

 int dce___fxstatat (int __ver,int __fildes,char const * __filename,stat * __stat_buf,int __flag) noexcept;

 int dce_fstat64 (int __fd, struct stat64 *__buf) noexcept;


#ifdef __cplusplus
}
#endif
#endif
