
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_MMAN_H
#define DCE_HEADER_SYS_MMAN_H
// TODO add extern "C" ?
#include <sys/mman.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void * dce_mmap (void *,size_t,int,int,int,__off_t);

 void * dce_mmap64 (void *,size_t,int,int,int,__off64_t);

 int dce_munmap (void *,size_t);


#ifdef __cplusplus
}
#endif
#endif
