
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_IOCTL_H
#define DCE_HEADER_SYS_IOCTL_H
// TODO add extern "C" ?
#include <sys/ioctl.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_ioctl (int,long unsigned int,...);


#ifdef __cplusplus
}
#endif
#endif
