
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_STATVFS_H
#define DCE_HEADER_SYS_STATVFS_H
// TODO add extern "C" ?
#include <sys/statvfs.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_statvfs (const char *path, struct statvfs *buf) noexcept;

 int dce_fstatvfs (int __fildes, struct statvfs * __buf) noexcept;


#ifdef __cplusplus
}
#endif
#endif
