
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_TIME_H
#define DCE_HEADER_SYS_TIME_H
// TODO add extern "C" ?
#include <sys/time.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_gettimeofday (__restrict__ ::timeval *,__timezone_ptr_t);

 int dce_setitimer (__itimer_which_t,__restrict__ ::itimerval const *,__restrict__ ::itimerval *);

 int dce_getitimer (__itimer_which_t,itimerval *);


#ifdef __cplusplus
}
#endif
#endif
