
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_WAIT_H
#define DCE_HEADER_SYS_WAIT_H
// TODO add extern "C" ?
#include <sys/wait.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 pid_t dce_wait (void *stat_loc);

 __pid_t dce_waitpid (__pid_t,int *,int);


#ifdef __cplusplus
}
#endif
#endif
