
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_SELECT_H
#define DCE_HEADER_SYS_SELECT_H
// TODO add extern "C" ?
#include <sys/select.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_select (int __nfds,__restrict__ ::fd_set * __readfds,__restrict__ ::fd_set * __writefds,__restrict__ ::fd_set * __exceptfds,__restrict__ ::timeval * __timeout);


#ifdef __cplusplus
}
#endif
#endif
