
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_SYSINFO_H
#define DCE_HEADER_SYS_SYSINFO_H
// TODO add extern "C" ?
#include <sys/sysinfo.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_sysinfo (struct sysinfo *info) ;


#ifdef __cplusplus
}
#endif
#endif
