
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_SYSLOG_H
#define DCE_HEADER_SYS_SYSLOG_H
// TODO add extern "C" ?
#include <sys/syslog.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 void dce_openlog (char const *,int,int);

 void dce_closelog ();

 int dce_setlogmask (int);

 void dce_syslog (int,char const *,...);

 void dce_vsyslog (int,char const *,va_list);


#ifdef __cplusplus
}
#endif
#endif
