
/* DO NOT MODIFY - GENERATED BY script */
#ifndef DCE_HEADER_SYS_STAT_H
#define DCE_HEADER_SYS_STAT_H
// TODO add extern "C" ?
#include <sys/stat.h>
// TODO temporary hack
#define __restrict__

#ifdef __cplusplus
extern "C" {
#endif
                 int dce_mkdir (char const * __path,__mode_t __mode) noexcept;

 __mode_t dce_umask (__mode_t __mask) noexcept;

 int dce_fstat64 (int __fd, struct stat64 *__buf) noexcept;


#ifdef __cplusplus
}
#endif
#endif
