## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf
import os

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'netanim', 'mobility' ], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'netanim', 'mobility'],
				  target='bin/dce-mt3',
				  source=['dce-mt3.cc'],
				  )
