## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'netanim'], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'netanim' ],
				  target='bin/dce-ping',
				  source=['dce-ping.cc', 'misc-tools.cc'],
#				  linkflags=['-L/usr/local/lib'],
#				  lib=['foolib']
				  )

