#!/bin/bash
#
# Build LKL (the Linux Kernel Library) for DCE.
#
# DCE loads a separate copy of the kernel library for each node. liblkl.so
# is relinked without default libraries, so that its few libc references
# bind to the simulator's libc, and stripped, since each node gets a copy;
# the debug information is kept in liblkl.so.debug, which gdb finds through
# the library's debug link.
#
# Usage: ./utils/build_lkl.sh [lkl_dir] [out_dir]
#   lkl_dir: LKL source tree, cloned if missing (default: ../lkl)
#   out_dir: where liblkl.so and the LKL headers (include/) are written
#            (default: <lkl_dir>/dce)
#   JOBS:    parallel make jobs (default: nproc)
#
# Configure DCE with --with-lkl=<out_dir> and add <out_dir> to DCE_PATH.
#
# The patches in utils/lkl-patches are applied first: see the commit
# message in each of them. The kernel is configured with LKL's defconfig
# plus utils/lkl-dce.config.
#

set -e

DCE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LKL_DIR="${1:-${DCE_DIR}/../lkl}"
LKL_REV="d0f76a77e8c2ca68bd7d96190b8da09040eab072" # LKL master, Linux 6.12, 2026-09-28
JOBS="${JOBS:-$(nproc)}"

if [ ! -d "${LKL_DIR}" ]; then
    # Shallow fetch of the pinned commit: the full history is several GB.
    git init -q "${LKL_DIR}"
    git -C "${LKL_DIR}" fetch -q --depth 1 https://github.com/lkl/linux "${LKL_REV}"
    git -C "${LKL_DIR}" -c advice.detachedHead=false checkout -q FETCH_HEAD
fi
LKL_DIR="$(cd "${LKL_DIR}" && pwd)"
if [ "$(git -C "${LKL_DIR}" rev-parse HEAD)" != "${LKL_REV}" ]; then
    echo "${LKL_DIR} is not at ${LKL_REV}: delete it to fetch it again." >&2
    exit 1
fi

for patch in "${DCE_DIR}"/utils/lkl-patches/*.patch; do
    if git -C "${LKL_DIR}" apply --reverse --check "${patch}" 2> /dev/null; then
        continue # already applied
    fi
    git -C "${LKL_DIR}" apply "${patch}"
done
OUT_DIR="${2:-${LKL_DIR}/dce}"

DEFCONFIG="${LKL_DIR}/arch/lkl/configs/dce_defconfig"
cat "${LKL_DIR}/arch/lkl/configs/defconfig" "${DCE_DIR}/utils/lkl-dce.config" > "${DEFCONFIG}.new"
if ! cmp -s "${DEFCONFIG}.new" "${DEFCONFIG}"; then
    mv "${DEFCONFIG}.new" "${DEFCONFIG}"
    rm -f "${LKL_DIR}/.config" # reconfigure
else
    rm "${DEFCONFIG}.new"
fi

make -C "${LKL_DIR}/tools/lkl" -j"${JOBS}" KCONFIG=dce_defconfig > "${LKL_DIR}/dce-build.log" 2>&1 \
    || { tail -50 "${LKL_DIR}/dce-build.log"; exit 1; }

mkdir -p "${OUT_DIR}"
gcc -shared -nostdlib -o "${OUT_DIR}/liblkl.so" \
    -Wl,--whole-archive "${LKL_DIR}/tools/lkl/liblkl.a" -Wl,--no-whole-archive \
    -Wl,-z,noexecstack
(
    cd "${OUT_DIR}"
    objcopy --only-keep-debug liblkl.so liblkl.so.debug
    objcopy --strip-debug --add-gnu-debuglink=liblkl.so.debug liblkl.so
)

# The headers DCE is built with (some are generated by the build).
rm -rf "${OUT_DIR}/include"
cp -a "${LKL_DIR}/tools/lkl/include" "${OUT_DIR}/include"

echo "Built ${OUT_DIR}/liblkl.so"
echo "Configure DCE with --with-lkl=${OUT_DIR} and add ${OUT_DIR} to DCE_PATH."
