## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
	conf.load('compiler_c')
	conf.load('compiler_cxx')
	ns3waf.check_modules(conf, ['core'], mandatory = True)
	 
def build(bld):
	bld.program(source='tenseconds.c', target='../../bin_dce/tenseconds', cflags = [ '-fPIC'], linkflags    = ['-pie', '-rdynamic'])
	bld.build_a_script('dce', needed = ['core', 'dce' ], target='bin/dce-sleep', source=['dce-sleep.cc'] )
