## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    pass

def build(bld):
    if bld.env['MPI']:
         bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'mpi'],
		   		            target='bin/dce-mpi-udp',
				            source=['dce-mpi-udp.cc'],				            
				            )

